import { Inter } from "next/font/google";
import ModalProvider from "@/components/providers/ModalProvider";
import PreviewProvider from "@/components/providers/PreviewProvider";
// import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <script src="https://code.jquery.com/jquery-3.6.0.slim.min.js"></script>
        <script src={"/bootstrap.bundle.min.js"}></script>
        <script src={"/bootstrap.min.js"}></script>
        <script src={"/custom.js"}></script>
        <script src={"/html5shiv.js"}></script>
        <script src={"/owl.carousel.min.js"}></script>
        <script src={"/respond.min.js"}></script>
        <script src={"/ie10-viewport-bug-workaround"}></script>
        {/* <ChakraUIProvider> */}
        <ModalProvider>
          <PreviewProvider>{children}</PreviewProvider>
        </ModalProvider>
        {/* </ChakraUIProvider> */}
      </body>
    </html>
  );
}
